export * as topSalesActions from './TopSales/actions'
export * as productActions from './Product/actions'
export * as categoriesActions from './Categories/actions'
export * as catalogActions from './Catalog/actions'
export * as cartActions from './Cart/actions'
export * as orderActions from './Order/actions'
