export const ORDER_SENT = 'ORDER_SENT'
export const ORDER_SENT_SUCCESS = 'ORDER_SENT_SUCCESS'
export const ORDER_SENT_FAIL = 'ORDER_SENT_FAIL'
export const ORDER_SENT_ERROR_CLEAR = 'ORDER_SENT_ERROR_CLEAR'

export const ORDER_CLEAR = 'ORDER_CLEAR'
