export const TOP_SALES_LOAD = 'TOP_SALES_LOAD'
export const TOP_SALES_LOAD_SUCCESS = 'TOP_SALES_LOAD_SUCCESS'
export const TOP_SALES_LOAD_FAIL = 'TOP_SALES_LOAD_FAIL'
export const TOP_SALES_LOAD_ERROR_CLEAR = 'TOP_SALES_LOAD_ERROR_CLEAR'

export const TOP_SALES_SET = 'TOP_SALES_SET'
export const TOP_SALES_CLEAR = 'TOP_SALES_CLEAR'
