export const CATEGORIES_LOAD = 'CATEGORIES_LOAD'
export const CATEGORIES_LOAD_SUCCESS = 'CATEGORIES_LOAD_SUCCESS'
export const CATEGORIES_LOAD_FAIL = 'CATEGORIES_LOAD_FAIL'
export const CATEGORIES_LOAD_ERROR_CLEAR = 'CATEGORIES_LOAD_ERROR_CLEAR'

export const CATEGORIES_SET = 'CATEGORIES_SET'
export const CATEGORIES_CLEAR = 'CATEGORIES_CLEAR'
