export const PRODUCT_LOAD = 'PRODUCT_LOAD'
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS'
export const PRODUCT_LOAD_FAIL = 'PRODUCT_LOAD_FAIL'
export const PRODUCT_LOAD_ERROR_CLEAR = 'PRODUCT_LOAD_ERROR_CLEAR'

export const PRODUCT_SET = 'PRODUCT_SET'
export const PRODUCT_CLEAR = 'PRODUCT_CLEAR'
